---
- name: Converge
  hosts: all
  become: true
  pre_tasks:
    - name: "Pre-task | Update apt-cache"
      apt:
        update_cache: true
        cache_valid_time: 600
      when: "ansible_os_family == 'Debian'"

  tasks:
    - name: "Include symplegma-os_bootstrap"
      include_role:
        name: "symplegma-os_bootstrap"
